name: Simple CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: '18'

jobs:
  test:
    name: Simple Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run basic tests
        run: |
          echo "Testing basic functionality..."
          npm test -- tests/isolated.test.js
          npm test -- tests/minimal.test.js
          npm test -- tests/ci-debug.test.js
        env:
          NODE_ENV: test
          JWT_SECRET: test-secret-key
          PORT: 4001
