name: Simple CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: '18'

jobs:
  test:
    name: Simple CI Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create test environment
        run: |
          echo "NODE_ENV=test" > .env
          echo "JWT_SECRET=test-secret-key-for-simple-ci" >> .env
          echo "PORT=4001" >> .env

      - name: Run linting
        run: npm run lint

      - name: Run simple CI tests
        run: npm run test:ci-simple
        env:
          NODE_ENV: test
          JWT_SECRET: test-secret-key-for-simple-ci
          PORT: 4001

      - name: Run app startup tests
        run: npm run test:ci-startup
        env:
          NODE_ENV: test
          JWT_SECRET: test-secret-key-for-simple-ci
          PORT: 4001

      - name: Run comprehensive CI tests
        run: npm run test:ci
        env:
          NODE_ENV: test
          JWT_SECRET: test-secret-key-for-simple-ci
          PORT: 4001
